# Generated by Django 2.1 on 2018-08-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('available_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('purchase_date', models.DateTimeField(verbose_name='date published')),
                ('photo_1', models.CharField(max_length=200)),
                ('photo_2', models.CharField(max_length=200)),
                ('photo_3', models.CharField(max_length=200)),
                ('photo_4', models.CharField(max_length=200)),
                ('photo_5', models.CharField(max_length=200)),
                ('photo_6', models.CharField(max_length=200)),
                ('proof_of_purchase', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
