# Generated by Django 2.1 on 2018-08-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('colour', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='in mm')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='in mm')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='in mm')),
            ],
            bases=('assets.baseasset',),
        ),
        migrations.AlterField(
            model_name='baseasset',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
