# Generated by Django 2.1 on 2018-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180809_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseasset',
            name='price',
        ),
        migrations.AlterField(
            model_name='baseasset',
            name='available_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GBP', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='baseasset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GBP', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=7, null=True),
        ),
    ]
