# Generated by Django 2.1 on 2018-08-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180809_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
