# Generated by Django 2.1 on 2018-08-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180809_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('power_draw', models.DecimalField(blank=True, decimal_places=2, help_text='Amps', max_digits=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'appliances',
            },
            bases=('assets.baseasset',),
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name_plural': 'furniture'},
        ),
    ]
