# Generated by Django 2.1 on 2018-08-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180809_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('disc_format', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('assets.baseasset',),
        ),
        migrations.RemoveField(
            model_name='baseasset',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='baseasset',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='baseasset',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='baseasset',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='furniture',
            name='photo_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='photo_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='photo_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='photo_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
