# Generated by Django 2.1 on 2018-08-09 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180809_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('catagory', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'other',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'technology',
            },
            bases=('assets.baseasset',),
        ),
        migrations.AddField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
