# Generated by Django 2.1 on 2018-08-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180809_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disc',
            name='num_discs',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of Discs'),
        ),
    ]
