# Generated by Django 2.1 on 2018-08-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180809_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('author', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
                ('genre', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
                ('book_format', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
                ('ISBN', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
                ('edition', models.CharField(blank=True, choices=[(0, 'Audio CD'), (1, 'DVD'), (2, 'Blu-Ray'), (3, 'UHD 4K'), (4, '3D'), (5, 'PS1'), (6, 'PS2'), (7, 'PS3'), (8, 'PS4'), (9, 'Wii'), (10, 'PC Game'), (11, 'PC Software'), (12, 'Other')], max_length=200, null=True)),
            ],
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Camping',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
                ('pack_quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Electronics',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Kitchenware',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Kitchenware',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Electronics',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='PuzzlesAndGames',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Puzzles and Games',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Sport',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Stationary',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            options={
                'verbose_name_plural': 'Stationary',
            },
            bases=('assets.baseasset',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.BaseAsset')),
            ],
            bases=('assets.baseasset',),
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name_plural': 'Other'},
        ),
    ]
